const actionTypes = {
  BOOKS_LOADING: 'BOOKS_LOADING',
  BOOKS_LOAD_SUCCESS: 'BOOKS_LOAD_SUCCESS',
  BOOKS_LOAD_FAILURE: 'BOOKS_LOAD_FAILURE',
  BOOK_ADDING: 'BOOK_ADDING',
  BOOK_ADD_SUCCESS: 'BOOK_ADD_SUCCESS',
  BOOK_ADD_FAILURE: 'BOOK_ADD_FAILURE',
};

export default actionTypes;
